In [1]:
import numpy as np       #linaer algebra
import pandas as pd       #data processing
import matplotlib.pyplot as plt       #data visualization
import seaborn as sns      #statistical data visualization
%matplotlib inline       

In [2]:
import warnings

warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('car_evaluation.csv', header = None)

In [4]:
df.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

In [5]:
df.shape

(1728, 7)

In [6]:
col_names = ['buying','maint','doors','persons','lug_boot','safety','class']

df.columns = col_names

col_names

['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [7]:
df.info()  #for checking if any missing value is available

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [8]:
df['class'].value_counts()

unacc    1210
acc       384
good       69
vgood      65
Name: class, dtype: int64

In [9]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [10]:
X = df.drop(['class'], axis=1)
y = df['class']

In [11]:
#split data into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [12]:
X_train.shape, X_test.shape

((1157, 6), (571, 6))

In [13]:
X_train.dtypes

buying      object
maint       object
doors       object
persons     object
lug_boot    object
safety      object
dtype: object

In [14]:
X_train.head()

buying  maint  doors persons lug_boot safety
48    vhigh  vhigh      3    more      med    low
468    high  vhigh      3       4    small    low
155   vhigh   high      3    more    small   high
1721    low    low  5more    more    small   high
1208    med    low      2    more    small   high

In [15]:
pip install category_encoders

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [16]:
import category_encoders as ce

In [17]:
encoder = ce.OrdinalEncoder(cols=['buying','maint','doors', 'persons', 'lug_boot', 'safety'])

X_train = encoder.fit_transform(X_train)

X_test = encoder.transform(X_test)

In [18]:
X_train.head()

buying  maint  doors  persons  lug_boot  safety
48         1      1      1        1         1       1
468        2      1      1        2         2       1
155        1      2      1        1         2       2
1721       3      3      2        1         2       2
1208       4      3      3        1         2       2

In [19]:
X_test.head()

buying  maint  doors  persons  lug_boot  safety
599        2      2      4        3         1       2
1201       4      3      3        2         1       3
628        2      2      2        3         3       3
1498       3      2      2        2         1       3
1263       4      3      4        1         1       1

In [38]:
#import Random Forest classifier 
from sklearn.ensemble import RandomForestClassifier

#instantiate the classifier
rfc = RandomForestClassifier(random_state=0)

#fit the model
rfc.fit(X_train, y_train)

#Predict the test set results
y_pred = rfc.predict(X_train)
y_pred = rfc.predict(X_test)

#Check accuracy score
from sklearn.metrics import accuracy_score
#print('Model accuracy score with 10 decision-trees: {0:04f}'.format(accuracy_score(y_train, y_pred)))
print('Model accuracy score with 10 decision-trees: {0:04f}'.format(accuracy_score(y_test, y_pred)))

Model accuracy score with 10 decision-trees: 0.945709


In [39]:
#create the classifier with n_estimaters = 100
clf = RandomForestClassifier(n_estimators=100, random_state=0)

#fit the model to the training set
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [44]:
#Print the Confusion Matrix and slice it into four pieces
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix\n\n',cm)

Confusion matrix

 [[114   9   4   2]
 [  2  17   0   1]
 [  8   0 389   0]
 [  3   2   0  20]]


In [45]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         acc       0.90      0.88      0.89       129
        good       0.61      0.85      0.71        20
       unacc       0.99      0.98      0.98       397
       vgood       0.87      0.80      0.83        25

    accuracy                           0.95       571
   macro avg       0.84      0.88      0.85       571
weighted avg       0.95      0.95      0.95       571

