In [10]:
def LinearSearch(array,n,k):
    for j in range(0,n):
        if(array[j] == k):
            return j
    return -1
    
array=[1,3,5,7,9]
k=7
n=len(array)
result=LinearSearch(array,n,k)
if(result == -1):
    print("Element not found")
else:
    print("Element found at index: ",result)
    

Element found at index:  3


In [18]:
#Iterative Method
def binarySearch(arr,k,low,high):
    
    while low <= high:
        mid = low + (high-low)//2
        if arr[mid] == k:
            return mid
        elif arr[mid] < k:
            low = mid +1
        else:
            high = mid-1
    return -1
arr = [1,3,5,7,9]
k=5
result = binarySearch(arr,k,0,len(arr)-1)
if result !=1:
    print("Element is present at index: " +str(result))
else:
    print("Element not found")

Element is present at index2


In [19]:
import numpy
Myarray= numpy.array([1,2,3,4])
print(Myarray)

[1 2 3 4]


In [26]:
numpy.__version__

'1.21.5'

In [33]:
arr= numpy.array(100)
#print(arr)
print(type(arr))

<class 'numpy.ndarray'>


In [35]:
twoD= numpy.array([[1,2,3],[4,5,6]])
print(twoD)

[[1 2 3]
 [4 5 6]]


In [36]:
arr=[1,2,3]
print(arr)

[1, 2, 3]


In [38]:
elem= [[1,2,3,4],[9,8,7,6]]
twoD= numpy.array(elem)
print(twoD)

[[1 2 3 4]
 [9 8 7 6]]


In [39]:
twoD.ndim

2

In [41]:
elem=[1,2,3,4]
oneD= numpy.array(elem)
print(oneD)

[1 2 3 4]


In [42]:
oneD.ndim

1

In [44]:
x=numpy.zeros(5,dtype=int)
x

array([0, 0, 0, 0, 0])

In [45]:
x=numpy.zeros((2,3),dtype=float)
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
x=numpy.ones((5,5),dtype=int)
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [51]:
#Less Memory
#sys.getsizeof(1) #Return memory size

import numpy as np

import sys #This module provides access to some variables used or maintained by

l=[1,2,3,4,5,6,7,8,9]
print(sys.getsizeof(l)*len(l))

arr= np.array(l)
print(arr.size*arr.itemsize)

1368
36
