In [1]:
import numpy as np

In [2]:
x = np.array([-2,-1,0,1,2])
np.absolute(x)

array([2, 1, 0, 1, 2])

In [4]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)

array([ 0., 10., 20., 30., 40.])

In [7]:
x = np.arange(1,101).reshape(10,10)
print(x)
x[:,[1]]

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


array([[ 2],
       [12],
       [22],
       [32],
       [42],
       [52],
       [62],
       [72],
       [82],
       [92]])

In [8]:
print(" Sum of Elements ", np.sum(x[:,[1]]))
print(" Product pf Elements ", np.prod(x[:,[1]]))
print(" Mean of Elements ",np.mean(x[:,[1]]))
print(" Standard deviation ",np.std(x[:,[1]]))
print(" Minimum Value ",np.min(x[:,[1]]))
print(" Maximum Value ",np.max(x[:,[1]]))
print(" Median ",np.median(x[:,[1]]))
print(" Any element are True: ",np.any(x[:,[1]]))

 Sum of Elements  470
 Product pf Elements  189267968
 Mean of Elements  47.0
 Standard deviation  28.722813232690143
 Minimum Value  2
 Maximum Value  92
 Median  47.0
 Any element are True:  True


In [9]:
x = np.array([1,2,3,4,5,np.nan,6,7,8,9])
np.nanmean(x)

5.0

In [18]:
def myufunc(x):
    return x**2

In [19]:
x = np.arange(1,11)
y = np.frompyfunc(myufunc,1,1)
y(x)

array([1, 4, 9, 16, 25, 36, 49, 64, 81, 100], dtype=object)

In [13]:
x = np.random.randint(1,10,size=10)
print(x)

[1 2 6 3 7 2 9 7 9 3]


In [15]:
np.where(x==9)

(array([6, 8], dtype=int64),)

In [16]:
np.where(x>4)

(array([2, 4, 6, 7, 8], dtype=int64),)

In [20]:
x = np.array([34,2,45,5,6,8,1,4])
np.sort(x)

array([ 1,  2,  4,  5,  6,  8, 34, 45])

In [23]:
data = np.random.randint(10,100,(10,4))
data

array([[85, 77, 16, 26],
       [24, 93, 74, 21],
       [50, 55, 18, 15],
       [86, 16, 68, 93],
       [87, 89, 91, 82],
       [36, 71, 16, 77],
       [47, 39, 60, 48],
       [79, 22, 85, 57],
       [91, 83, 16, 32],
       [89, 67, 67, 18]])

In [24]:
np.sort(data,axis=0)

array([[24, 16, 16, 15],
       [36, 22, 16, 18],
       [47, 39, 16, 21],
       [50, 55, 18, 26],
       [79, 67, 60, 32],
       [85, 71, 67, 48],
       [86, 77, 68, 57],
       [87, 83, 74, 77],
       [89, 89, 85, 82],
       [91, 93, 91, 93]])

In [25]:
np.sort(data,axis=1)

array([[16, 26, 77, 85],
       [21, 24, 74, 93],
       [15, 18, 50, 55],
       [16, 68, 86, 93],
       [82, 87, 89, 91],
       [16, 36, 71, 77],
       [39, 47, 48, 60],
       [22, 57, 79, 85],
       [16, 32, 83, 91],
       [18, 67, 67, 89]])

In [28]:
np.sort(data[:,[1]],axis=0)

array([[16],
       [22],
       [39],
       [55],
       [67],
       [71],
       [77],
       [83],
       [89],
       [93]])

In [32]:
x = np.array([1,2,3,4,5])
f = [True, False, True, True, False]
x[f]

array([1, 3, 4])

In [33]:
x = np.array([1,2,3,4,5,6])
f = x%2==1
x[f]

array([1, 3, 5])

In [35]:
#Transposing Array
x = np.arange(1,10).reshape(3,3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
m = np.array([[1,2],[3,4],[5,6]])
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
np.rot90(m)

array([[2, 4, 6],
       [1, 3, 5]])